default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: grupal-tsundoku_development

test:
  <<: *default
  database: grupal-tsundoku_test

production:
  <<: *default
  database: grupal-tsundoku_production
  username: grupal-tsundoku
  password: <%= ENV['GRUPAL-TSUNDOKU_DATABASE_PASSWORD'] %>
